version: '3.7'

services:
   loratrust-emqx:
    container_name: mqtt-broker
    image: emqx/emqx:5.1.0
    environment:
      - "EMQX_BRIDGES__WEBHOOK__BACKEND__BODY=\"$${payload}\""
      - "EMQX_BRIDGES__WEBHOOK__BACKEND__CONNECT_TIMEOUT=15s"
      - "EMQX_BRIDGES__WEBHOOK__BACKEND__ENABLE_PIPELINING=100"
      - "EMQX_BRIDGES__WEBHOOK__BACKEND__HEADERS={\"content-type\" = \"application/json\"}"
      - "EMQX_BRIDGES__WEBHOOK__BACKEND__METHOD=post"
      - "EMQX_BRIDGES__WEBHOOK__BACKEND__POOL_SIZE=8"
      - "EMQX_BRIDGES__WEBHOOK__BACKEND__POOL_TYPE=random"
      - "EMQX_BRIDGES__WEBHOOK__BACKEND__RESOURCE_OPTS__AUTO_RESTART_INTERVAL=60s"
      - "EMQX_BRIDGES__WEBHOOK__BACKEND__RESOURCE_OPTS__HEALTH_CHECK_INTERVAL=15s"
      - "EMQX_BRIDGES__WEBHOOK__BACKEND__RESOURCE_OPTS__INFLIGHT_WINDOW=100"
      - "EMQX_BRIDGES__WEBHOOK__BACKEND__RESOURCE_OPTS__MAX_BUFFER_BYTES=1GB"
      - "EMQX_BRIDGES__WEBHOOK__BACKEND__RESOURCE_OPTS__QUERY_MODE=async"
      - "EMQX_BRIDGES__WEBHOOK__BACKEND__RESOURCE_OPTS__REQUEST_TIMEOUT=15s"
      - "EMQX_BRIDGES__WEBHOOK__BACKEND__RESOURCE_OPTS__WORKER_POOL_SIZE=4"
      - "EMQX_BRIDGES__WEBHOOK__BACKEND__SSL__ENABLE=false"
      - "EMQX_BRIDGES__WEBHOOK__BACKEND__SSL__VERIFY=verify_peer"
      - "EMQX_BRIDGES__WEBHOOK__BACKEND__URL=http://demo2.loratrust.com:18080/save_data"
      - "EMQX_RULE_ENGINE__IGNORE_SYS_MESSAGE=true"
      - "EMQX_RULE_ENGINE__JQ_FUNCTION_DEFAULT_TIMEOUT=10s"
      - "EMQX_RULE_ENGINE__RULES__RULE_4XSC__ACTIONS__1=webhook:backend"
      - "EMQX_RULE_ENGINE__RULES__RULE_4XSC__DESCRIPTION=ingest mqtt topic to backend"
      - "EMQX_RULE_ENGINE__RULES__RULE_4XSC__METADATA={\"created_at\" = 1688553193098}"
      - "EMQX_RULE_ENGINE__RULES__RULE_4XSC__SQL=\"SELECT payload FROM \\\"to-server/#\\\"\""
    ports:
      - 1883:1883
      - 127.0.0.1:8883:8883
      - 127.0.0.1:8084:8084
      - 127.0.0.1:18083:18083

