MQTT_WEIGHTS_BATCH_SIZE = 100

SCALED_WEIGHT_BITS = 16

INPUT_NODES = 650
OUTPUT_NODES = 4
HIDDEN_NODES = 5

SIZE_HIDDEN_LAYER = (INPUT_NODES+1) * HIDDEN_NODES
SIZE_OUTPUT_LAYER = (HIDDEN_NODES+1) * OUTPUT_NODES